// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClk9hUPTQ9eYo5QSnOnhx_Fs4O5E8rl6U',
    appId: '1:250735074464:web:87509632aede0618233dc5',
    messagingSenderId: '250735074464',
    projectId: 'planner-dima',
    authDomain: 'planner-dima.firebaseapp.com',
    storageBucket: 'planner-dima.appspot.com',
    measurementId: 'G-JZGE2ZTHYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2tTQFvMzwIryRI8wRMGszv3mGSwikBo',
    appId: '1:250735074464:android:6dc8848d83bcea48233dc5',
    messagingSenderId: '250735074464',
    projectId: 'planner-dima',
    storageBucket: 'planner-dima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2cCiWaRDQP6OWs3IIS8_wsreGd-4jzsA',
    appId: '1:250735074464:ios:0ce2deae4b7a2701233dc5',
    messagingSenderId: '250735074464',
    projectId: 'planner-dima',
    storageBucket: 'planner-dima.appspot.com',
    iosClientId: '250735074464-bi1dp4obai3c7q8kpbdba1jm61bvd045.apps.googleusercontent.com',
    iosBundleId: 'com.example.plannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2cCiWaRDQP6OWs3IIS8_wsreGd-4jzsA',
    appId: '1:250735074464:ios:0ce2deae4b7a2701233dc5',
    messagingSenderId: '250735074464',
    projectId: 'planner-dima',
    storageBucket: 'planner-dima.appspot.com',
    iosClientId: '250735074464-bi1dp4obai3c7q8kpbdba1jm61bvd045.apps.googleusercontent.com',
    iosBundleId: 'com.example.plannerApp',
  );
}
